pp-issue93-allowed-user
Sintrop/core-contracts pull request #107
Opened 2022-08-08 18:35 UTC by pjvperes

#93 

- Configure  the function newAllowedUser to Advisors and Contributors
- Edit AdvisorContract and ContributorContract tests.js

2022-08-12 12:55 UTC, rav-andre approved these changes

2022-08-12 13:19 UTC, everson-ever requested changes
Da uma olhada quando puder man

2022-08-12 13:19 UTC, everson-ever commented on contracts/AdvisorContract.sol
> +  ) public uniqueAdvisor mustBeAllowedUser returns (Advisor memory) {
Nesse caso aqui, vc pode inverter a ordem pra a checagem de allowedUser acontecer primeiro

2022-08-12 13:19 UTC, everson-ever commented on contracts/ContributorContract.sol
> +  ) public uniqueContributor mustBeAllowedUser returns (Contributor memory) {
Nesse caso aqui tbm. Vc pode inverter a ordem pra a checagem de allowedUser acontecer primeiro

2022-08-12 13:19 UTC, everson-ever commented on test/AdvisorContract.test.js
> -          await addAdvisor("Advisor B", adv2Address);
Pra esses casos onde vc tirou o `adv2Address` por ele não ser um `allowedUser` pois ia dar problema, vc pode configurar pra ele ser um `allowedUser` **apenas pra esses contextos que vc precisa** OU vc pode criar uma `adv3Address` e configurar ele como `allowedUser` igual vc fez com `adv1Address`.

No geral, seria bom usar dois usuários nesses specs que vc tirou o `adv2Address`

2022-08-12 13:19 UTC, everson-ever commented on test/ContributorContract.test.js
>        context("when contributor don't exists", () => {
Mesma observação do outro

2022-08-15 22:45 UTC, everson-ever requested changes
Só esse ponto e manda ver

2022-08-15 22:45 UTC, everson-ever commented on test/AdvisorContract.test.js
> +
Só ficou uma linha em branch aqui man!

2022-08-16 01:04 UTC, pjvperes commented on test/AdvisorContract.test.js
> +
Boaa, vou corrigir agora mesmo já!

2022-08-16 11:30 UTC, everson-ever approved these changes

2022-08-16 11:55 UTC, merged