Rav researcher allowed isa
Sintrop/core-contracts pull request #115
Opened 2022-08-17 19:30 UTC by rav-andre

Solving merge conflicts

2022-08-20 02:03 UTC, everson-ever requested changes
Meu review

2022-08-20 02:03 UTC, everson-ever commented on test/CategoryContract.test.js
>    it("should create category with votes equal 0", async () => {
Esse spec pode ficar dentro do contexto da linha 81 tbm, pois está relacionado a criação de uma categoria

2022-08-22 10:58 UTC, rav-andre commented on .github/workflows/main.yml
> +        run: ganache-cli -a 10 -e 100 -q &
beleza, corrigido!

2022-08-22 10:59 UTC, rav-andre commented on test/CategoryContract.test.js
> +
removido

2022-08-22 11:00 UTC, rav-andre commented on test/CategoryContract.test.js
> +});
Adicionado

2022-08-22 11:01 UTC, rav-andre commented on test/CategoryContract.test.js
>    it("should create category", async () => {
removido

2022-08-22 11:06 UTC, rav-andre commented on test/CategoryContract.test.js
>    it("should add msg.sender in createdBy", async () => {
feito

2022-08-22 11:10 UTC, rav-andre commented on test/CategoryContract.test.js
>    it("should increment total of categories after a new is added", async () => {
alterado

2022-08-24 14:22 UTC, rav-andre commented on test/CategoryContract.test.js
>    it("should create category with votes equal 0", async () => {
feito

2022-08-24 15:00 UTC, everson-ever requested changes
Só esse ponto! Os demais pontos parecem ok

2022-08-24 15:00 UTC, everson-ever commented on test/Sintrop.test.js
> +});
Não vi esse ponto aqui! Está sem linha final em branco

2022-08-24 15:01 UTC, everson-ever approved these changes

2022-08-24 18:17 UTC, merged