45-update-activist-inspections-security
Sintrop/core-contracts pull request #120
Opened 2022-08-29 16:29 UTC by orcus69

2022-08-29 22:41 UTC, everson-ever requested changes
Só esses dois pontos man!

- Remover esses espaços
- Mudar de lugar o spec e alterar o texto do it

2022-08-29 22:41 UTC, everson-ever commented on test/Sintrop.test.js
> +      { from: address }
Esses espaços a mais vc pode remover!
Tem alguns outros nesse PR!

Vamos ver uma issue pra configurar um code quality pra esse projeto!

2022-08-29 22:41 UTC, everson-ever commented on test/Sintrop.test.js
>    context("when activist try accept inspection not OPEN", () => {
Pode colocar o novo spec aqui abaixo desse aqui aqui

```javascript
  context("when activist try accept inspection of the same producer", () => {
    it("should return error message", async () => {
      await instance.requestInspection({ from: producerAddress });
      await instance.acceptInspection(1, { from: activistAddress });
      await instance.realizeInspection(1, [], { from: activistAddress });

      await expectRevert(
        instance.acceptInspection(1, { from: activistAddress }),
        "Already inspected this producer"
      );
    });
  });
```

2022-09-01 00:27 UTC, rav-andre approved these changes

2022-09-01 00:33 UTC, everson-ever approved these changes

2022-09-01 18:05 UTC, merged