limit voting numbers
Sintrop/core-contracts pull request #129
Opened 2022-09-10 01:49 UTC by orcus69

2022-09-10 13:30 UTC, everson-ever requested changes
Pode editar tbm CHANGELOG
`We limit the number of votes a user can vote for a category to 100K`

2022-09-10 13:30 UTC, everson-ever commented on test/CategoryContract.test.js
> +      { from: from }
Tem várias alterações de `lint` nesse spec, no entanto seu spec é apenas o da linha 156.
Pode remover essas alterações de lint e deixar somente seu spec que dá certo!


Observação: `ESTAMOS PRA CONFIGURAR UM LINTER NA PIPELINE PARA .sol e .js`

2022-09-10 13:30 UTC, everson-ever commented on test/CategoryContract.test.js
Tem uma linha em branco aqui

2022-09-10 13:32 UTC, everson-ever requested changes
Alguns pequenos ajustes no contrato

2022-09-10 13:32 UTC, everson-ever commented on contracts/CategoryContract.sol
> +   modifier mustNotExceedLimitVoting(uint256 id, uint256 tokens){
Identação incorreta

2022-09-10 13:32 UTC, everson-ever commented on contracts/CategoryContract.sol
> +  uint256 public constant LIMIT_VOTING = 100000000000000000000000;
Pode adicionar uma linha em branco entre a constant e os mappings

2022-10-11 18:27 UTC, everson-ever commented on test/CategoryContract.test.js
> +        context("when send at least 1 SAC token to vote", () => {
Acredito que não precise alterar o contexto, certo?

Esse contexto está testando quando o usuário não envia nenhum token, o sistema deve dizer que ele deve enviar ao menos 1

2022-10-11 22:14 UTC, orcus69 commented on test/CategoryContract.test.js
> +        context("when send at least 1 SAC token to vote", () => {
vdd, blz. tinha entendido errado

2022-10-12 11:20 UTC, everson-ever approved these changes

2022-10-12 12:03 UTC, merged