set migrations with initial users and isa category #113
Sintrop/core-contracts pull request #137
Opened 2022-09-26 14:13 UTC by pjvperes

Issue #113 

To help front-end development, we will add to migrations commands to create automatically initial users and one test isa category.

User 1 - Producer 1 (producer1)
User 2 - Producer 2 (producer2)
User 3 - Activist 1 (activist1)
User 4 - Activist 2 (activist2)
User 5 - Researcher 1 (researcher1)

Also one category (category1), created by Researcher 1.

2022-09-26 21:14 UTC, rav-andre requested changes
Apenas necessário alterar o nome do activist 1, de resto tudo funcionando como esperado!

2022-09-26 21:14 UTC, rav-andre commented on migrations/2_deploy_contracts.js
> +    "activist2",
Aqui deveria ser "activist 1".

2022-09-26 21:42 UTC, everson-ever reviewed
Alguns ajustes que acho que ficariam legal. O que vc acha?

2022-09-26 21:42 UTC, everson-ever commented on migrations/2_deploy_contracts.js
> +    let accounts = await web3.eth.getAccounts()
@pjvperes  Vamos começar a dividir nossas migrações em arquivos, mas precisamos ver como exatamente funciona aqui no truffle, então seria uma boa vc adicionar todas essas alterações em um outro arquivo chamado

`3_set_initial_users_and_categories.js`

dentro desse arquivo vc adicionaria a estrutura padrão e carregaria os contratos deployados que vc precisar

```javascript
const CategoryContract = artifacts.require("CategoryContract");

module.exports = function (deployer) {
  const categoryContract = await CategoryContract.deployed();

  await categoryContract.addCategory(
    "category1",
    `the description of category1`,
    `how activists should evaluate category1`,
    `category1 totallySustainable`,
    `category1 partiallySustainable`,
    `category1 neutro`,
    `category1 partiallyNotSustainable`,
    `category1 totallyNotSustainable`,
    {from: researcher1});
  });
}
```

Seria interessante tbm colocar dados mais reais nos recursos criados. @rav-andre  Vc pode ajudá-lo nesse sentido?

2022-09-27 17:22 UTC, rav-andre approved these changes

2022-10-01 13:37 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +        await deployer.deploy(ResearcherContract, UserContract.address);
Acredito que vc não precise fazer deploy de  novo nesse migração, pois já foi feito na anterior!

Aqui vc só precisaria pegar o contrato deployado.

```javascript
const researcherContract = await ResearcherContract.deployed();
```

2022-10-01 13:37 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +      };
Um espaço entre a constant e o método abaixo ficaria bom

2022-10-01 13:37 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +    let accounts = await web3.eth.getAccounts()
essas duas linhas vc pode jogar pra fora desse método se for possível

2022-10-01 13:37 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +const SacToken = artifacts.require("SacToken");
Pelo que vi vc só precisa carregar os contratos 

```
CategoryContract
ProducerContract
ResearcherContract
ActivistContract
```

2022-10-01 13:37 UTC, everson-ever requested changes
Pode avaliar os comentários que coloquei?

2022-10-01 19:48 UTC, pjvperes commented on migrations/3_set_initial_users_and_categories.js
> +const SacToken = artifacts.require("SacToken");
Tentei rodar aqui, mas deu ruim. Parece que precisa desses demais contratos, pois esses 4 contratos que você citou precisa dos demais.

2022-10-01 19:49 UTC, pjvperes commented
Sobre as demais alterações, acabei de realizar aqui e já irei fazer o commit.

2022-10-01 20:36 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +const SacToken = artifacts.require("SacToken");
IsaPool precisaria?

Vi que vc está usando no deploy de `categoryContract`, mas o deploy de `categoryContract` foi feito na migration anterior

2022-10-01 20:37 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +const SacToken = artifacts.require("SacToken");
O mesmo pra o SacToken

2022-10-01 20:38 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +        const userContract = await UserContract.deployed();
Acredito que não precise de userContract tbm, nem do deploy (pois iria substituir o deploy anterior), nem de pegar o userContract deployado

2022-10-01 20:39 UTC, everson-ever commented on migrations/3_set_initial_users_and_categories.js
> +        await userContract.newAllowedCaller(activistContract.address);
Essas ações aqui já foram feitas na migration anterior

2022-10-01 20:41 UTC, everson-ever requested changes
# Sugestão de código

```javascript
const CategoryContract = artifacts.require("CategoryContract");
const ProducerContract = artifacts.require("ProducerContract");
const ResearcherContract = artifacts.require("ResearcherContract");
const ActivistContract = artifacts.require("ActivistContract");

module.exports = function (deployer) {
  deployer.then(async () => {
    let accounts = await web3.eth.getAccounts();
    let [producer1, producer2, activist1, activist2, researcher1] = accounts;

    const categoryContract = await CategoryContract.deployed();
    const activistContract = await ActivistContract.deployed();
    const producerContract = await ProducerContract.deployed();
    const researcherContract = await ResearcherContract.deployed();

    await researcherContract.newAllowedUser(researcher1);

    await producerContract.addProducer(
      "Beans Farm",
      "123456789123456",
      "CNPJ",
      "Brazil",
      "São Paulo",
      "São Carlos",
      "123456789123456",
      {from: producer1}
    );

    await producerContract.addProducer(
      "Soy Plantation",
      "11111111111111",
      "CNPJ",
      "Brazil",
      "São Paulo",
      "Piracicaba",
      "1111111111111",
      {from: producer2}
    );

    await activistContract.addActivist(
      "John Johnson",
      "22222222222222",
      "CPF",
      "Brazil",
      "SP",
      "Ribeirão Preto",
      "2222222222222222",
      {from: activist1}
    );

    await activistContract.addActivist(
      "Peter Parker",
      "3333333333333",
      "CPF",
      "Brazil",
      "SP",
      "Marília",
      "333333333333333",
      {from: activist2}
    );

    await researcherContract.addResearcher(
      "Researcher Tom",
      "444444444444444",
      "CPF",
      "Brazil",
      "SP",
      "Bauru",
      "44444444444444",
      {from: researcher1}
    );

    await categoryContract.addCategory(
      "Pesticides use",
      `the description of category1`,
      `how activists should evaluate category1`,
      `category1 totallySustainable`,
      `category1 partiallySustainable`,
      `category1 neutro`,
      `category1 partiallyNotSustainable`,
      `category1 totallyNotSustainable`,
      {from: researcher1}
    );
  });
};

```

2022-10-14 16:55 UTC, closed without merging