producer pool
Sintrop/core-contracts pull request #163
Opened 2022-12-03 13:20 UTC by everson-ever

# #141

2022-12-03 13:46 UTC, everson-ever commented
# Script para testar via console

Carregar contratos
```js
var sintrop = await Sintrop.deployed()
var producerContract = await ProducerContract.deployed()
var producerPool = await ProducerPool.deployed()
```


## SINTROP - Requisitando inspeção e realizando-a

- Requisitar uma inspeção com um produtor já cadastrado
```js
await sintrop.requestInspection({ from: accounts[1] })
```

- Aceitar inspeção qeu foi requisitada acima com um ativista já cadastrado
```js
await sintrop.acceptInspection(1, { from: accounts[2] })
```

- Realizar inspeção (Após execução do código abaixo o produtor vai ficar com 10 `isaScore`)
```js
await sintrop.realizeInspection(1, [{categoryId: 1, isaIndex: 0, report: "Solo A totalmente sustentável", proofPhoto: "Hash_1"}], { from: accounts[2] })
```


## PRODUCER CONTRACT
- Pegar produtor que teve a inspeção realizada
  - O isaScore dele deve ser 10 `producer.isa.isaScore`
  - O total de inspeções dele deve ser 1 `producer.totalInspections`
```js
await producerContract.getProducer(accounts[1])
```

- Chamar o método de sacar tokens (Não deve conseguir sacar pois não tem o mínimo de inspeções requeridas)
OBS: **Se quiser testar o saque, deverá ter 3 inspeções realizadas ou editar no código pra 1 o número de inspeções requeridas pra sacar**
```js
await producerContract.withdraw({ from: accounts[1] })
```

## PRODUCER POOL


- Tokens por era
```js
var tokensPerEra = await producerPool.tokensPerEra()
tokensPerEra.toString()
```

- Era atual do contrato
```js
var currentContractEra = await producerPool.currentContractEra()
currentContractEra.toString()
```

- Balance do contrato
```js
var balance= await producerPool.balance()
balance.toString()
```

- Balance do produtor
```js
var balanceOf = await producerPool.balanceOf(accounts[1])
balanceOf.toString()
```

2022-12-12 19:30 UTC, rav-andre requested changes
De forma geral, muito legal o código dessa nova implementação muito importante pro sistema.

Adicionei alguns comentários simples.

Está faltando criar as issues dos comentários //TODOs escritos no código, acho que seria bom fazer isso antes de aprovar esse merge.

O que senti que está faltando ainda pra essa atualização é a questão das 12 eras no máximo. Acha que faz sentido implementar nesse PR ainda? Qual a questão/dificuldade desse ponto??

Outra coisa que está faltando é a função onlyOwner para banir o usuário e remover da pool. 
O que pensei é adicionar talvez um bool a nível do produtor que começa false, do tipo bool ban. E aí criar uma função onlyOwner que altera esse bool para true caso o usuário seja delatado. E então nas funções de cálculo do isaScoreMax remover os usuários banidos. Acha que faz sentido implementar já ou adicionar issue pra isso?

2022-12-14 21:32 UTC, everson-ever commented on contracts/ProducerContract.sol
> +  int256 internal constant MAXIMUM_ISA_SCORE_POOL = 1000;
Faz sentido! Vou ajustar!!

2022-12-14 21:38 UTC, everson-ever commented on contracts/ProducerContract.sol
> +    // TODO: Create issue to create producer instance before, so add just the required fields
Esse TODO seria pra configurarmos/avaliar a criação do Producer partir da seguinte estrutura

```solidity
Producer memory producer;

producer["name"] = name
producer["proofPhoto"] = proofPhoto
.
.
.

producers[msg.sender] = producer;
```

Assim nós adicionariamos somente os valores que estão vindo via parâmetros ou obrigatórios. O demais atributos receberiam os valores defaults do seus tipos.


**OBS**: Ainda teriamos de avaliar o custo em gas dessa alteração

2022-12-14 21:38 UTC, everson-ever commented on contracts/ProducerContract.sol
> +    require(minimumInspections(producer.totalInspections), "minimum inspections");
Vou ajustar!! Vlw

2022-12-14 21:40 UTC, everson-ever commented on contracts/ProducerContract.sol
> +  int256 internal constant MAXIMUM_ISA_SCORE_POOL = 1000;
A ação de banir usuário da pool será desenvolvida em uma issue posterior

2022-12-17 18:33 UTC, rav-andre commented on contracts/ProducerContract.sol
> +    // TODO: Create issue to create producer instance before, so add just the required fields
E qual a vantagem da mudança de estrutura?

2022-12-17 18:36 UTC, rav-andre commented on contracts/ProducerContract.sol
> +  uint256 internal constant MINIMUM_INSPECTION_TO_POOL = 1;
No caso esse valor seria 3 não? Mínimo de 3 inspeções para chamar a pool.

2022-12-17 21:10 UTC, everson-ever commented on contracts/ProducerContract.sol
> +    // TODO: Create issue to create producer instance before, so add just the required fields
A vantangem é que a gente não precisaria setar o o valor de um campo que começa com o valor padrão dele.

Quando estamos criando o produtor do  jeito que tá nós somos obrigados a setar o valor  de `lastRequestAt` que já tem o seu valor base como `0`.

Do jeito que estou propondo analisarmos nós só setariamos os valores que vem via parâmetro

2022-12-17 21:11 UTC, everson-ever commented on contracts/ProducerContract.sol
> +  uint256 internal constant MINIMUM_INSPECTION_TO_POOL = 1;
Vdd! Mudei o valor quando estava testando e esqueci de voltar! vlw

2022-12-17 21:12 UTC, everson-ever commented on contracts/ProducerContract.sol
> +  uint256 internal constant MINIMUM_INSPECTION_TO_POOL = 1;
Ajustado

2022-12-19 17:39 UTC, rav-andre commented on contracts/ProducerContract.sol
> +    // TODO: Create issue to create producer instance before, so add just the required fields
Humm reduzindo o gas né, legal agora acho que entendi.

2022-12-19 17:42 UTC, rav-andre approved these changes

2022-12-20 11:12 UTC, merged