Refactoring specs UserContract
Sintrop/core-contracts pull request #73
Opened 2022-06-18 17:48 UTC by orcus69

Refactoring test by adding a context

2022-06-18 18:46 UTC, everson-ever requested changes

2022-06-18 18:46 UTC, everson-ever commented on test/UserContract.test.js
> +        await instance.newAllowedCaller(user1Address, { from: user1Address })
Aqui pode usar o `expectRevert`, tem exemplos na linha `56`! Por algum motivo os specs começaram a quebrar quando testamos o caso de erro desse jeito que está agora!

2022-06-18 18:46 UTC, everson-ever commented on test/UserContract.test.js
> -  it("should increment usersCount when add new user", async () => {
Esse spec acabou sumindo! Podes adicionar ele abaixo da linha `44`, pois o contexto da certo pra esse tbm, concorda?

2022-06-18 18:46 UTC, everson-ever commented on test/UserContract.test.js
> +    context("to Undefined", () => {
Esse spec não precisa, pois a ideia do tipo `Undefined` seria um usuário que não foi cadastrado no sistema! Podemos adicionar uma feature pra bloquear cadastro de usuários com o tipo `Undefined` e uma função pra checar a existência de um usuário que, no caso iria trabalhar junto com o modifier que já existe! Vou criar essas duas issues!

2022-06-18 18:46 UTC, everson-ever commented on test/UserContract.test.js
> +  context("when enum correctly to users", () => {
O spec pra checar o correto Enum pra o tipo `Producer` ficou faltando aqui. Podes adicionar pfv?

2022-06-24 16:50 UTC, everson-ever commented on test/UserContract.test.js
> -  it("should increment usersCount when add new user", async () => {
Vi que vc adicionou o spec pra esse caso! Se puder adicioná-lo dentro do contexto da linha `52`

Algo assim (Só ajustar a identação): 

```javascript
context("when the user exists", () => {
        it("should return error message", async () => {
          await addUser(user1Address, userTypes.Producer, owner);

          await expectRevert(
            addUser(user1Address, userTypes.Producer, owner),
            "User already exists"
          );
        });

        it("should increment usersCount when add new user", async () => {
          await addUser(user1Address, userTypes.Producer, owner);

          const usersCount = await instance.usersCount();
      
          assert.equal(usersCount, 1);
        });
      });
});
```

2022-06-24 18:06 UTC, orcus69 commented on test/UserContract.test.js
> -  it("should increment usersCount when add new user", async () => {
Corrigido

2022-06-24 18:23 UTC, everson-ever commented on test/UserContract.test.js
> +        it("should usersCount be zero when not has user", async () => {
Esse aqui pode fica fora mesmo man! Não faz parte desse contexto! 

Vc pode criar um novo contexto pra ele, por exemplo

```javascript
context("when don't has users", () => {
    it("should usersCount be zero", async () => {
      const usersCount = await instance.usersCount();
  
      assert.equal(usersCount, 0);
    });
})
```

2022-06-24 22:18 UTC, orcus69 commented on test/UserContract.test.js
> +        it("should usersCount be zero when not has user", async () => {
Feito

2022-06-24 22:29 UTC, everson-ever approved these changes

2022-06-29 03:36 UTC, merged