creation of ContributorsContract
Sintrop/core-contracts pull request #80
Opened 2022-06-20 23:00 UTC by rav-andre

add ContributorsContract.sol
add ContributorTypes.sol

2022-06-20 23:39 UTC, everson-ever commented
Atualiza o CHANGELOG.md pfv!

2022-06-20 23:40 UTC, everson-ever requested changes

2022-06-20 23:40 UTC, everson-ever commented on contracts/ContributorContract.sol
> +  function addContributor(
Quem vai registrar um contributor? O próprio usuário ou o owner?

2022-06-20 23:40 UTC, everson-ever commented on contracts/ContributorContract.sol
> +contract ContributorContract is Callable {
Esse Callable não está sendo utilizado. Esse contrato tem um modifier chamado `mustBeAllowedCaller` que permite apenas que alguns endereços chamem determinado método!
Por exemplo se apenas o owner puder cadastrar um Contribuidor, então deve-se usar `mustBeAllowedCaller`  em `addContributor` e dar acesso ao owner de chamar esse método

2022-06-20 23:42 UTC, rav-andre commented on contracts/ContributorContract.sol
> +  function addContributor(
A proposta é que seja aberto para que qualquer usuário se cadastre como contribuidor. Porém que somente o owner consiga adicioná-los na futura ContributorsPool 1.0.

2022-06-20 23:45 UTC, everson-ever commented on contracts/ContributorContract.sol
> +  function addContributor(
Ok! Então esse método está ok! Só remover o comentários da linha 30

2022-06-20 23:48 UTC, everson-ever commented on contracts/ContributorContract.sol
> +contract ContributorContract is Callable {
Pode remover o import da linha 6 e o Callable! 

Alinhei com o @rav-andre que o cadastro de contribuidores vai ser aberto e não vamos precisar setar permissões pra métodos no momento!

2022-06-21 03:06 UTC, rav-andre commented on contracts/ContributorContract.sol
> +contract ContributorContract is Callable {
@everson-ever certeza que precisa remover o callable?? Esse não é o contrato que vai exigir que o endereço do ContributorsContract.sol seja adicionado no UserContract??

Ao remover o import e o callable todos os testes quebram.

2022-06-21 11:23 UTC, everson-ever commented on contracts/ContributorContract.sol
> +contract ContributorContract is Callable {
Sim, pois não está sendo utilizado dentro do contrato! Se está quebrando é pq tem algum problema no spec

2022-06-21 12:57 UTC, rav-andre commented on contracts/ContributorContract.sol
> +contract ContributorContract is Callable {
Beleza. Resolvido aqui e changelog adicionado.

2022-06-22 11:04 UTC, everson-ever requested changes

2022-06-22 11:04 UTC, everson-ever commented on test/ContributorContract.test.js
> +
Adiciona esse código na linha `28`, vc acabou removendo por engano.
A outra linha que foi removida está ok!!

```javascript
await userContract.newAllowedCaller(instance.address);
```

2022-06-22 11:07 UTC, everson-ever commented on CHANGELOG.md
> +## [1.0.1]() (2022-06-21 HHhMM)
Não precisa adicionar uma nova versão! Adiciona esse texto junto aos demais, no mesmo padrão

2022-06-22 13:33 UTC, rav-andre commented on CHANGELOG.md
> +## [1.0.1]() (2022-06-21 HHhMM)
Feito.

2022-06-22 15:07 UTC, merged