pp-issue-71-update-isaPoints-to-isaScore
Sintrop/core-contracts pull request #87
Opened 2022-07-04 22:35 UTC by pjvperes

#71

2022-07-05 00:14 UTC, rav-andre approved these changes

2022-07-05 00:30 UTC, everson-ever reviewed
O arquivo Sintrop.test.js está com muitas alterações de um `lint` (ajuestes de estilização). Isso é algo que temos de ver como configuração do projeto ainda. Enquanto não temos isso vc poderia alterar somente linhas necessárias desse arquivo?

2022-07-05 00:31 UTC, everson-ever requested changes
O arquivo Sintrop.test.js está com muitas alterações de um lint (ajuestes de estilização). Isso é algo que temos de ver como configuração do projeto ainda. Enquanto não temos isso vc poderia alterar somente linhas necessárias desse arquivo?

2022-07-05 00:34 UTC, everson-ever commented on contracts/Sintrop.sol
>     * @dev Sum the ISA points
Esse comment poderia ser ajustado tbm pra `@dev Sum the ISA Score`

2022-07-11 13:16 UTC, everson-ever commented on test/Sintrop.test.js
> +    it("show return all inspectionfrom mapping", async () => {
Ficou faltando uma espaço entre as palavras

2022-07-11 13:17 UTC, everson-ever commented on test/Sintrop.test.js
> +    it("should accept inspection with successwhen is OPEN", async () => {
Ficou faltando uma espaço entre as palavras

2022-07-11 13:17 UTC, everson-ever commented on test/Sintrop.test.js
> +    it("should remove 10 isaScorefrom inspection when select totallyNotSustainable", async () => {
Ficou faltando uma espaço entre as palavras

2022-07-11 13:20 UTC, everson-ever reviewed
Pode adicionar o  CHANGELOG tbm

2022-07-11 14:18 UTC, everson-ever approved these changes

2022-07-11 14:23 UTC, merged